// Generated by CoffeeScript 1.10.0
(function() {
  var config, handler, qs, request;

  request = require('request');

  qs = require('qs');

  config = require('config').service.monternet;

  handler = function(callback) {
    return function(err, res, body) {
      if (!err && res.statusCode === 200) {
        return callback(null, body);
      } else {
        return callback(body || true);
      }
    };
  };

  module.exports = function(phone, msg, callback) {
    var uri;
    uri = qs.stringify({
      userId: config.user,
      password: config.pass,
      pszMobis: phone,
      pszMsg: msg,
      iMobiCount: 1,
      pszSubPort: '*',
      MsgId: 0
    });
    return request({
      url: "" + config.host + config.sendApi + "?" + uri,
      json: true,
      headers: {
        'user-agent': 'teambition'
      }
    }, handler(callback));
  };

}).call(this);
