// Generated by CoffeeScript 1.10.0
(function() {
  var config, port, redis, ref, server;

  redis = require('redis');

  config = require('config');

  ref = config.REDIS_CONFIG, server = ref.server, port = ref.port;

  module.exports = redis.createClient(port, server);

}).call(this);
