// Generated by CoffeeScript 1.10.0
(function() {
  var config, twilio;

  config = require('config').service.twilio;

  twilio = require('twilio');

  twilio = twilio(config.accountSid, config.authToken);

  module.exports = function(phone, msg, callback) {
    return twilio.sendMessage({
      from: config.from,
      to: phone,
      body: msg
    }, callback);
  };

}).call(this);
