// Generated by CoffeeScript 1.9.1
(function() {
  var db;

  db = require('limbo').use('anmoyi');

  module.exports = {
    init: function(req, res, next) {
      var _placeId, _userId;
      _userId = req.session._userId;
      _placeId = req.session._placeId;
      req._data = {};
      if (_userId) {
        return db.user.findOneAsync({
          _id: _userId
        }).then(function(user) {
          if (user) {
            console.log('init', user);
            req._data.user = user;
          }
          return next();
        });
      } else if (_placeId) {
        return db.place.findOneAsync({
          _id: _placeId
        }).then(function(place) {
          if (place) {
            req._data.user = place;
          }
          return next();
        });
      } else {
        return next();
      }
    },
    isRoot: function(req, res, next) {
      var user;
      user = req._data.user;
      if (user && user.role === 'root') {
        return next();
      } else {
        return res.status(403).send('Forbidden');
      }
    },
    isAgent: function(req, res, next) {
      var ref, user;
      user = req._data.user;
      if (user && ((ref = user.role) === 'agent' || ref === 'root')) {
        return next();
      } else {
        return res.status(403).send('Forbidden');
      }
    },
    isLogined: function(req, res, next) {
      var user;
      user = req._data.user;
      console.log('isLogined', user);
      if (user) {
        return next();
      } else {
        return res.status(403).send('Forbidden');
      }
    }
  };

}).call(this);
