// Generated by CoffeeScript 1.9.1
(function() {
  var U, _, crypto, qrcodeConf, uuid;

  _ = require('lodash');

  qrcodeConf = require('config').wxConfig;

  uuid = require('uuid');

  crypto = require('crypto');

  U = {
    v1: function() {
      return uuid.v1().replace(/-/g, '');
    },
    v4: function() {
      return uuid.v4().replace(/-/g, '');
    },
    md5: function(str) {
      var md5sum;
      md5sum = crypto.createHash('md5');
      md5sum.update(str);
      str = md5sum.digest('hex');
      return str;
    },
    sha1: function(str) {
      return crypto.createHash('sha1').update(str).digest('hex');
    },
    qsParseSortByAscii: function(data) {
      var arr, keys;
      keys = Object.keys(data);
      keys.sort();
      arr = [];
      keys.forEach(function(key) {
        if (data[key]) {
          return arr.push(key + "=" + data[key]);
        }
      });
      return arr.join('&');
    },
    json2xml: function(obj) {
      var str;
      str = "<xml>";
      Object.keys(obj).forEach(function(key) {
        return str += "<" + key + ">" + obj[key] + "</" + key + ">";
      });
      str += "</xml>";
      return str;
    }
  };

  module.exports = U;

}).call(this);
