// Generated by CoffeeScript 1.9.1
(function() {
  var DailyRotateFile, File, _, ref, winston;

  winston = require('winston');

  _ = require('lodash');

  ref = winston.transports, File = ref.File, DailyRotateFile = ref.DailyRotateFile;

  module.exports = new winston.Logger({
    levels: {
      debug: 1,
      info: 2,
      warn: 3,
      error: 4,
      confirm: 5
    },
    transports: [
      new DailyRotateFile({
        level: 'info',
        filename: 'daily_info',
        dirname: 'logs/daily',
        name: 'infodaily'
      }), new DailyRotateFile({
        level: 'warn',
        filename: 'daily_error',
        dirname: 'logs/error',
        name: 'errdaily'
      }), new File({
        level: 'confirm',
        filename: 'confirm.log',
        dirname: 'logs'
      })
    ]
  });

}).call(this);
