// Generated by CoffeeScript 1.9.1
(function() {
  var WXPay, appid, body, detail, generateWxSign, host, ip, key, mch_id, ref, ref1, request, total_fee, u, wx_date, wxpay;

  ref = require('config').wxConfig, mch_id = ref.mch_id, appid = ref.appid, body = ref.body, detail = ref.detail, total_fee = ref.total_fee, key = ref.key;

  ref1 = require('config'), ip = ref1.ip, host = ref1.host;

  u = require('./services/util');

  request = require('request');

  WXPay = require('weixin-pay');

  wxpay = WXPay({
    appid: appid,
    mch_id: mch_id,
    partner_key: key
  });

  wx_date = function(date) {
    var str;
    if (date) {
      date = new Date(date);
    } else {
      date = new Date;
    }
    str = date.toJSON();
    return str.replace(/-|T|:|.\d{3}Z/g, '');
  };

  generateWxSign = function(data) {
    var qsStr;
    qsStr = u.qsParseSortByAscii(data);
    qsStr += "&key=" + key;
    console.log(qsStr);
    return u.md5(qsStr).toUpperCase();
  };

  module.exports = {
    generateQrUrl: function(extra) {
      return wxpay.createMerchantPrepayUrl({
        product_id: '123456'
      });
    },
    unifiedorder: function(product_id, open_id, callback) {
      var data, query, url;
      url = 'https://api.mch.weixin.qq.com/pay/unifiedorder';
      data = {
        appid: appid,
        mch_id: mch_id,
        device_info: 'WEB',
        nonce_str: u.v4(),
        body: body,
        detail: detail,
        out_trade_no: product_id,
        total_fee: total_fee,
        spbill_create_ip: ip,
        time_start: wx_date(),
        notify_url: host + "/wx/notify",
        trade_type: "NATIVE",
        product_id: product_id,
        openid: openid
      };
      data.sign = generateWxSign(data);
      query = u.qsParseSortByAscii(data);
      return request.post({
        url: url,
        data: data,
        json: true
      }, function(err, res, body) {
        console.log(err, body);
        return callback(err, body);
      });
    }
  };

}).call(this);
