// Generated by CoffeeScript 1.9.1
(function() {
  var CronJob, db, todos;

  CronJob = require('cron').CronJob;

  todos = require('../scripts');

  db = require('limbo').use('teambition');

  new CronJob('00 00 12 * * 0', function() {
    return Object.keys(todos).forEach(function(todo) {
      return todos[todo]();
    });
  }, function() {
    return consol.log('job done');
  }, true);

}).call(this);
