// Generated by CoffeeScript 1.10.0
(function() {
  var controllers, files, fs;

  fs = require('fs');

  files = fs.readdirSync(__dirname);

  controllers = module.exports;

  files.forEach(function(file) {
    var ext, filename, ref;
    ref = file.split('.'), filename = ref[0], ext = ref[1];
    if (__dirname + '/' + file !== __filename) {
      return controllers[filename.toLowerCase()] = require("./" + filename);
    }
  });

}).call(this);
