// Generated by CoffeeScript 1.9.1
(function() {
  var config, getHost, setCookieURI;

  config = require('config');

  getHost = function(useProduction) {
    var host;
    if (useProduction == null) {
      useProduction = false;
    }
    host = "https://account.teambition.com";
    if (config.DEBUG && !useProduction) {
      host = "http://account.project.ci";
    }
    return host;
  };

  setCookieURI = '/weixin/setcookie';

  module.exports = {
    tplURL: function(next) {
      return config.MP_WEIXIN.successURL + config.PREFIX + '/tpl/message?next=' + encodeURIComponent(next);
    },
    indexURL: function(useProduction) {
      if (useProduction == null) {
        useProduction = false;
      }
      return getHost(useProduction) + config.PREFIX;
    },
    loginURL: function(useProduction, isMP) {
      if (useProduction == null) {
        useProduction = false;
      }
      if (isMP == null) {
        isMP = false;
      }
      if (isMP) {
        return config.MP_WEIXIN.successURL + '/#/wx_login';
      } else {
        return getHost(useProduction) + config.PREFIX + '/login';
      }
    },
    successURL: function(isMP, useProduction, setcookie) {
      if (isMP == null) {
        isMP = false;
      }
      if (useProduction == null) {
        useProduction = false;
      }
      if (setcookie == null) {
        setcookie = false;
      }
      if (isMP) {
        return this.mpSuccessURL(useProduction, setcookie);
      }
      if (setcookie) {
        return getHost(useProduction) + setCookieURI + '?state=' + config.WX_OPEN_PLATFORM.state;
      } else {
        return config.WX_OPEN_PLATFORM.successURL;
      }
    },
    mpSuccessURL: function(useProduction, setcookie) {
      if (useProduction == null) {
        useProduction = false;
      }
      if (setcookie == null) {
        setcookie = false;
      }
      if (setcookie) {
        return getHost(useProduction) + setCookieURI + '?state=' + config.MP_WEIXIN.state;
      } else {
        return config.MP_WEIXIN.successURL;
      }
    },
    redirectURL: function() {
      return getHost(true) + config.PREFIX + config.WX_OPEN_PLATFORM.redirectURI;
    },
    authURL: function(qs) {
      return config.WX_OPEN_PLATFORM.authURL + "?" + qs + '#' + config.WX_OPEN_PLATFORM.wechat_redirect;
    },
    bindErrorURL: function() {
      return config.WX_OPEN_PLATFORM.bindErrorURL;
    },
    getWXTokenURL: function(qs) {
      return config.WX_OPEN_PLATFORM.tokenURL + "?" + qs;
    },
    getMPTokenURL: function(qs) {
      return config.MP_WEIXIN.tokenURL + "?" + qs;
    },
    userInfoURL: function(qs, isMP) {
      if (isMP == null) {
        isMP = false;
      }
      if (isMP) {
        return this.openIdURL(qs);
      }
      return config.WX_OPEN_PLATFORM.userInfoURL + "?" + qs;
    },
    ticketURL: function(qs) {
      return config.MP_WEIXIN.ticketURL + "?" + qs;
    },
    getSetCookieURI: function() {
      return setCookieURI;
    },
    menuURL: "https://api.weixin.qq.com/cgi-bin/menu/create",
    openIdURL: function(qs) {
      return config.MP_WEIXIN.userInfoURL + "?" + qs;
    },
    messageURL: function(qs) {
      return config.MP_WEIXIN.msgURL + "?" + qs;
    },
    qrcodeURL: function(qs) {
      return config.MP_WEIXIN.qrcodeURL + "?" + qs;
    },
    getMPAuthURL: function(qs) {
      return config.MP_WEIXIN.authURL + "?" + qs;
    },
    getSendTemplateMsgURL: function(qs) {
      return config.MP_WEIXIN.templateURL + '?' + qs;
    }
  };

}).call(this);
