// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    var ActivenessSchma;
    return ActivenessSchma = new Schema({
      _projectId: {
        type: Schema.Types.ObjectId
      },
      _organizationId: {
        type: Schema.Types.ObjectId
      },
      count: Number,
      created: {
        type: Date,
        "default": Date.now
      },
      updated: {
        type: Date,
        "default": Date.now
      }
    }, {
      read: 'secondaryPreferred'
    });
  };

}).call(this);
