// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(Schema) {
    var Alien;
    Alien = new Schema({
      name: String,
      city: String,
      province: String,
      openId: String,
      country: String,
      money: {
        type: Number,
        "default": 0
      },
      created: {
        type: Date,
        "default": Date.now
      }
    });
    return Alien;
  };

}).call(this);
