// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    var deviceSchema;
    deviceSchema = new Schema({
      _userId: {
        type: Schema.Types.ObjectId
      },
      uid: String,
      name: String,
      lastUsed: {
        type: Date,
        "default": Date.now
      },
      _placeId: Schema.Types.ObjectId,
      status: {
        type: String,
        "default": 'init'
      },
      price: {
        type: Number,
        "default": 5
      },
      time: {
        type: Number,
        "default": 10
      },
      discount: {
        type: Number,
        "default": 100
      },
      remission: {
        type: Number,
        "default": 0
      },
      income: {
        type: Number,
        "default": 0
      },
      wxTime: {
        type: Number,
        "default": 0
      },
      created: {
        type: Date,
        "default": Date.now
      },
      updated: {
        type: Date,
        "default": Date.now
      },
      statusUpdated: {
        type: Date,
        "default": Date.now
      }
    }, {
      toObject: {
        virtuals: true,
        getters: true
      },
      toJSON: {
        virtuals: true,
        getters: true
      }
    });
    deviceSchema.virtual('cost').get(function() {
      return this.price * this.discount / 100 - this.remission;
    });
    deviceSchema.virtual('realStatus').get(function() {
      if (Date.now() - this.statusUpdated < 1000 * 60) {
        return this.status;
      } else {
        return 'fault';
      }
    });
    deviceSchema.methods.getPayInfo = function() {
      var info;
      info = {
        name: this.name,
        _placeId: this._placeId,
        cost: this.cost,
        status: this.status,
        time: this.time,
        uid: this.uid,
        _userId: this._userId,
        _placeId: this._placeId
      };
      return info;
    };
    return deviceSchema;
  };

}).call(this);
