// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    var deviceSchema;
    deviceSchema = new Schema({
      _userId: {
        type: Schema.Types.ObjectId
      },
      uid: String,
      name: String,
      lastUsed: {
        type: Date,
        "default": Date.now
      },
      _placeId: Schema.Types.ObjectId,
      status: {
        type: String,
        "default": 'stop'
      },
      price: {
        type: Number,
        "default": 5
      },
      time: {
        type: Number,
        "default": 10
      },
      discount: {
        type: Number,
        "default": 100
      },
      remission: {
        type: Number,
        "default": 0
      },
      income: {
        type: Number,
        "default": 0
      },
      wxTime: {
        type: Number,
        "default": 0
      },
      created: {
        type: Date,
        "default": Date.now
      },
      updated: {
        type: Date,
        "default": Date.now
      }
    }, {
      toObject: {
        virtuals: true,
        getters: true
      },
      toJSON: {
        virtuals: true,
        getters: true
      }
    });
    deviceSchema.virtual('cost').get(function() {
      return this.price * this.discount / 100 - this.remission;
    });
    deviceSchema.methods.getPayInfo = function() {
      var info;
      info = {
        name: this.name,
        place: this.place,
        cost: this.cost,
        status: this.status,
        time: 3,
        uid: this.uid,
        _userId: this._userId
      };
      return info;
    };
    return deviceSchema;
  };

}).call(this);
