// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    return new Schema({
      income: {
        type: Number,
        "default": 0
      },
      wxTime: {
        type: Number,
        "default": 0
      },
      uid: String,
      type: String,
      created: {
        type: Date,
        "default": Date.now
      }
    }, {
      read: 'secondaryPreferred'
    });
  };

}).call(this);
