// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    return {
      Device: require('./device')(Schema),
      User: require('./user')(Schema),
      Income: require('./income')(Schema),
      Order: require('./order')(Schema),
      Status: require('./status')(Schema)
    };
  };

}).call(this);
