// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(Schema) {
    var Place;
    Place = new Schema({
      name: String,
      province: String,
      city: String,
      district: String,
      company: String,
      email: String,
      mailAddress: String,
      qq: String,
      bankName: String,
      bankAccount: String,
      _salesmanId: Schema.Types.ObjectId,
      _agentId: Schema.Types.ObjectId,
      contacts: {
        type: Schema.Types.Mixed,
        "default": []
      },
      password: {
        type: String,
        "default": function() {
          return parseInt(Math.random() * 1000000 - 1);
        }
      },
      role: {
        type: String,
        "default": "place"
      },
      p: {
        type: Number,
        "default": 100
      },
      discount: {
        type: Number,
        "default": 100
      },
      remission: {
        type: Number,
        "default": 0
      },
      created: {
        type: Date,
        "default": Date.now
      },
      updated: {
        type: Date,
        "default": Date.now
      }
    });
    Place.virtual('location').get(function() {
      return this.province + "-" + this.city + "-" + this.district;
    });
    Place.methods.format = function() {
      var data;
      data = this.toJSON();
      delete data.password;
      return data;
    };
    return Place;
  };

}).call(this);
