// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    return new Schema({
      name: String,
      province: String,
      city: String,
      county: String,
      address: String,
      _agentId: Schema.Types.ObjectId,
      _userId: Schema.Types.ObjectId,
      contacts: {
        type: Schema.Types.Mixed,
        "default": []
      },
      created: {
        type: Date,
        "default": Date.now
      },
      updated: {
        type: Date,
        "default": Date.now
      }
    });
  };

}).call(this);
