// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    return new Schema({
      _organizationId: {
        type: Schema.Types.ObjectId
      },
      startDate: Date,
      ranks: Object,
      counts: Object,
      doneTasks: Array,
      delayTasks: Array,
      newTasks: Array
    });
  };

}).call(this);
