// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    return new Schema({
      status: {
        type: String,
        "default": ''
      },
      uid: String,
      created: {
        type: Date,
        "default": Date.now
      }
    }, {
      read: 'secondaryPreferred'
    });
  };

}).call(this);
