// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = {
    findWithQuery: function(options, query, callback) {
      var limit, page, sort;
      if (callback == null) {
        callback = function() {};
      }
      page = parseInt(query.page) || 1;
      limit = parseInt(query.limit || query.count) || 30;
      sort = query.sort || {
        _id: -1
      };
      if (query.maxDate != null) {
        options.created = {
          $lt: query.maxDate
        };
      }
      if (query.sinceDate) {
        options.created = {
          $gt: query.sinceDate
        };
      }
      return this.find(options).sort(sort).limit(limit).skip(limit * (page - 1)).exec(callback);
    }
  };

}).call(this);
