// Generated by CoffeeScript 1.9.1
(function() {
  var xss;

  xss = require('xss');

  module.exports = function(Schema, options) {
    return new Schema({
      _taskId: {
        type: Schema.Types.ObjectId,
        ref: 'Task',
        index: true
      },
      _projectId: {
        type: Schema.Types.ObjectId,
        ref: 'Project'
      },
      isDone: {
        es_indexed: true,
        type: Boolean,
        "default": false
      },
      _executorId: {
        type: Schema.Types.ObjectId,
        ref: 'User'
      },
      _creatorId: {
        type: Schema.Types.ObjectId,
        ref: 'User'
      },
      content: {
        es_indexed: true,
        es_analyzer: 'ik_smart',
        type: String,
        "default": '',
        get: function(val) {
          if (val != null) {
            return xss(val);
          } else {
            return val;
          }
        }
      },
      dueDate: {
        es_indexed: true,
        type: Date,
        "default": null
      },
      created: {
        es_indexed: true,
        type: Date,
        "default": Date.now
      },
      updated: {
        es_indexed: true,
        type: Date,
        "default": Date.now
      }
    }, {
      read: 'secondaryPreferred',
      toObject: {
        virtuals: true,
        getters: true
      },
      toJSON: {
        virtuals: true,
        getters: true
      }
    });
  };

}).call(this);
