// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(Schema) {
    return new Schema({
      name: {
        type: String,
        "default": 'default'
      },
      phone: String,
      email: String,
      location: String,
      company: String,
      mailAddress: String,
      qq: String,
      bankName: String,
      bankAccount: String,
      password: {
        type: String,
        "default": '888888'
      },
      role: {
        type: Number,
        "default": 0
      },
      type: String,
      created: {
        type: Date,
        "default": Date.now
      }
    }, {
      read: 'secondaryPreferred'
    });
  };

}).call(this);
