// Generated by CoffeeScript 1.10.0
(function() {
  var _;

  _ = require('lodash');

  module.exports = function(Schema) {
    var User;
    User = new Schema({
      name: {
        type: String,
        "default": 'default'
      },
      phone: String,
      email: String,
      location: String,
      company: String,
      mailAddress: String,
      qq: String,
      bankName: String,
      bankAccount: String,
      password: {
        type: String,
        "default": '888888'
      },
      role: String,
      created: {
        type: Date,
        "default": Date.now
      }
    });
    User.methods.hasOrder = function() {
      var ref;
      return (ref = this.type) === 'root' || ref === 'agent';
    };
    User.methods.format = function() {
      var data;
      if (this.role === 'agent') {
        data = _.pick(this, ['name', 'company', 'phone', 'location', 'email', 'mailAddress', 'qq', 'bankName', 'bankAccount', 'role']);
      } else {
        data = _.pick(this, ['name', 'phone', 'email', 'role']);
      }
      return data;
    };
    return User;
  };

}).call(this);
